apiVersion: v1
kind: Service
metadata:
  name: ssh-runner-service
  namespace: devtools
spec:
  clusterIP: None  # ğŸ‘ˆ Ğ”ĞµĞ»Ğ°ĞµÑ‚ ÑĞµÑ€Ğ²Ğ¸Ñ headless
  selector:
    app: ssh-runner
  ports:
    - name: ssh
      port: 22
      targetPort: 22
